# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'BreathingCoach' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BreathingCoach
  pod 'Starscream', '~> 4.0.6'

  target 'BreathingCoachTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BreathingCoachUITests' do
    # Pods for testing
  end

end
