# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '17.0'
use_frameworks!
source 'https://github.com/azawawi/SwiftyZeroMQ.git'

target 'BreathingCoach' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BreathingCoach
  pod 'SwiftyZeroMQ', '~> 1.0'

  target 'BreathingCoachTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BreathingCoachUITests' do
    # Pods for testing
  end

end
