function [Hd, b] = bpf_breath_10fs
%BPF_BREATH_10FS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 16-Nov-2021 18:50:07

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 10;  % Sampling Frequency

Fstop1 = 0.001;           % First Stopband Frequency
Fpass1 = 0.1;             % First Passband Frequency
Fpass2 = 1;               % Second Passband Frequency
Fstop2 = 1.25;            % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
